### ISSUE TITLE
Question: why are record labels not taken into consideration while applying Threshold / Uniform strategies

### ISSUE THREAD

**Issue by rvdwijngaard** [samber/slog-sampling#1]
Hi, I like the idea of this package. It was exactly something what we were looking for. I have one question. Both the Threshold and the Uniform strategies are based on the Log Level and the Message. Is there are particular reason why the keys are not taken into account? 

Background of this question is that I have a process with a high throughput. Each message has several attributes which are added a scoped logger, something like this. 
```
scopedLogger := logger.With("foo", "bar", "id", 1)
...
scopedLogger.Error("something bad happened", "err", err)
```
Because the sampling is done on Log Level and Message I have to change my code to something like this: 
```
logger.Error(fmt.Sprintf("something bad happened with foo %s, id %d, "foo", 1), "err", err)
```

**Comment by samber** [comment]
Hi @rvdwijngaard 

You can use a custom sampling strategy:

```go
option := slogsampling.CustomSamplingOption{
    Sampler: func(ctx context.Context, record slog.Record) float64 {
          // return a value between 0 and 1, based on attributes located in record.Attrs
    },
}
```

**Comment by rvdwijngaard** [comment]
Hi @samber 

Thanks for your suggestion. I'll follow your suggestion. 

Wouldn't it be a nice enhancement of the ThresholdSamplingOption to configure the key of the hash? I find it very useful that this option applies sampling on the actual message instead of just applying a rate on all messages. On the other hand I understand things easily gets complicated if you add too many options.

**Comment by samber** [comment]
I'm going to create a new issue to track this improvement.
